<?php
declare(strict_types=1);

use Migrations\AbstractSeed;

/**
 * Profiles seed.
 */
class ProfilesSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * https://book.cakephp.org/phinx/0/en/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'name' => 'matsumoto',
                'user_device' => 'PC',
                'os' => 'Mac',
                'age' => 25,
                'country' => 'Japan',
                'created' => '2020-01-01 10:00:00',
                'modified' => '2020-01-01 10:00:00',
            ],
            [
                'name' => 'tokino',
                'user_device' => 'PC',
                'os' => 'Mac',
                'age' => 25,
                'country' => 'Japan',
                'created' => '2020-01-02 10:00:00',
                'modified' => '2020-01-02 10:00:00',
            ],
            [
                'name' => 'admin',
                'user_device' => 'PC',
                'os' => 'Mac',
                'age' => 25,
                'country' => 'Japan',
                'created' => '2020-01-03 10:00:00',
                'modified' => '2020-01-03 10:00:00',
            ],
            [
                'name' => 'matsumoto',
                'user_device' => 'スマホ',
                'os' => 'Mac',
                'age' => 25,
                'country' => 'Japan',
                'created' => '2020-01-04 10:00:00',
                'modified' => '2020-01-04 10:00:00',
            ],
            [
                'name' => 'tokino',
                'user_device' => 'スマホ',
                'os' => 'Mac',
                'age' => 25,
                'country' => 'Japan',
                'created' => '2020-01-05 10:00:00',
                'modified' => '2020-01-05 10:00:00',
            ],
            [
                'name' => 'admin',
                'user_device' => 'スマホ',
                'os' => 'Mac',
                'age' => 25,
                'country' => 'Japan',
                'created' => '2020-01-06 10:00:00',
                'modified' => '2020-01-06 10:00:00',
            ],
            [
                'name' => 'matsumoto',
                'user_device' => 'PC',
                'os' => 'Windows',
                'age' => 25,
                'country' => 'Japan',
                'created' => '2020-01-07 10:00:00',
                'modified' => '2020-01-07 10:00:00',
            ],
            [
                'name' => 'tokino',
                'user_device' => 'PC',
                'os' => 'Windows',
                'age' => 25,
                'country' => 'Japan',
                'created' => '2020-01-08 10:00:00',
                'modified' => '2020-01-08 10:00:00',
            ],
            [
                'name' => 'admin',
                'user_device' => 'PC',
                'os' => 'Windows',
                'age' => 25,
                'country' => 'Japan',
                'created' => '2020-01-09 10:00:00',
                'modified' => '2020-01-09 10:00:00',
            ],
            [
                'name' => 'matsumoto',
                'user_device' => 'スマホ',
                'os' => 'Windows',
                'age' => 25,
                'country' => 'Japan',
                'created' => '2020-01-10 10:00:00',
                'modified' => '2020-01-10 10:00:00',
            ],
            [
                'name' => 'tokino',
                'user_device' => 'スマホ',
                'os' => 'Windows',
                'age' => 25,
                'country' => 'Japan',
                'created' => '2020-01-11 10:00:00',
                'modified' => '2020-01-11 10:00:00',
            ],
            [
                'name' => 'admin',
                'user_device' => 'スマホ',
                'os' => 'Windows',
                'age' => 25,
                'country' => 'Japan',
                'created' => '2020-01-12 10:00:00',
                'modified' => '2020-01-12 10:00:00',
            ],
            [
                'name' => 'matsumoto',
                'user_device' => 'PC',
                'os' => 'Mac',
                'age' => 25,
                'country' => 'USA',
                'created' => '2020-01-13 10:00:00',
                'modified' => '2020-01-13 10:00:00',
            ],
            [
                'name' => 'tokino',
                'user_device' => 'PC',
                'os' => 'Mac',
                'age' => 25,
                'country' => 'USA',
                'created' => '2020-01-14 10:00:00',
                'modified' => '2020-01-14 10:00:00',
            ],
            [
                'name' => 'admin',
                'user_device' => 'PC',
                'os' => 'Mac',
                'age' => 25,
                'country' => 'USA',
                'created' => '2020-01-15 10:00:00',
                'modified' => '2020-01-15 10:00:00',
            ],
            [
                'name' => 'matsumoto',
                'user_device' => 'スマホ',
                'os' => 'Mac',
                'age' => 25,
                'country' => 'USA',
                'created' => '2020-01-16 10:00:00',
                'modified' => '2020-01-16 10:00:00',
            ],
            [
                'name' => 'tokino',
                'user_device' => 'スマホ',
                'os' => 'Mac',
                'age' => 25,
                'country' => 'USA',
                'created' => '2020-01-17 10:00:00',
                'modified' => '2020-01-17 10:00:00',
            ],
            [
                'name' => 'admin',
                'user_device' => 'スマホ',
                'os' => 'Mac',
                'age' => 25,
                'country' => 'USA',
                'created' => '2020-01-18 10:00:00',
                'modified' => '2020-01-18 10:00:00',
            ],
            [
                'name' => 'matsumoto',
                'user_device' => 'PC',
                'os' => 'Mac',
                'age' => 25,
                'country' => 'China',
                'created' => '2020-01-19 10:00:00',
                'modified' => '2020-01-19 10:00:00',
            ],
            [
                'name' => 'tokino',
                'user_device' => 'PC',
                'os' => 'Mac',
                'age' => 25,
                'country' => 'China',
                'created' => '2020-01-20 10:00:00',
                'modified' => '2020-01-20 10:00:00',
            ],
            [
                'name' => 'admin',
                'user_device' => 'PC',
                'os' => 'Mac',
                'age' => 25,
                'country' => 'China',
                'created' => '2020-01-21 10:00:00',
                'modified' => '2020-01-21 10:00:00',
            ],
            [
                'name' => 'matsumoto',
                'user_device' => 'スマホ',
                'os' => 'Mac',
                'age' => 25,
                'country' => 'China',
                'created' => '2020-01-22 10:00:00',
                'modified' => '2020-01-22 10:00:00',
            ],
            [
                'name' => 'tokino',
                'user_device' => 'スマホ',
                'os' => 'Mac',
                'age' => 25,
                'country' => 'China',
                'created' => '2020-01-23 10:00:00',
                'modified' => '2020-01-23 10:00:00',
            ],
            [
                'name' => 'admin',
                'user_device' => 'スマホ',
                'os' => 'Mac',
                'age' => 25,
                'country' => 'China',
                'created' => '2020-01-24 10:00:00',
                'modified' => '2020-01-24 10:00:00',
            ],
            [
                'name' => 'matsumoto',
                'user_device' => 'PC',
                'os' => 'Mac',
                'age' => 35,
                'country' => 'Japan',
                'created' => '2020-02-01 10:00:00',
                'modified' => '2020-02-01 10:00:00',
            ],
            [
                'name' => 'tokino',
                'user_device' => 'PC',
                'os' => 'Mac',
                'age' => 35,
                'country' => 'Japan',
                'created' => '2020-02-02 10:00:00',
                'modified' => '2020-02-02 10:00:00',
            ],
            [
                'name' => 'admin',
                'user_device' => 'PC',
                'os' => 'Mac',
                'age' => 35,
                'country' => 'Japan',
                'created' => '2020-02-03 10:00:00',
                'modified' => '2020-02-03 10:00:00',
            ],
            [
                'name' => 'matsumoto',
                'user_device' => 'スマホ',
                'os' => 'Mac',
                'age' => 35,
                'country' => 'Japan',
                'created' => '2020-02-04 10:00:00',
                'modified' => '2020-02-04 10:00:00',
            ],
            [
                'name' => 'tokino',
                'user_device' => 'スマホ',
                'os' => 'Mac',
                'age' => 35,
                'country' => 'Japan',
                'created' => '2020-02-05 10:00:00',
                'modified' => '2020-02-05 10:00:00',
            ],
            [
                'name' => 'admin',
                'user_device' => 'スマホ',
                'os' => 'Mac',
                'age' => 35,
                'country' => 'Japan',
                'created' => '2020-02-06 10:00:00',
                'modified' => '2020-02-06 10:00:00',
            ],
            [
                'name' => 'matsumoto',
                'user_device' => 'PC',
                'os' => 'Windows',
                'age' => 35,
                'country' => 'Japan',
                'created' => '2020-02-07 10:00:00',
                'modified' => '2020-02-07 10:00:00',
            ],
            [
                'name' => 'tokino',
                'user_device' => 'PC',
                'os' => 'Windows',
                'age' => 35,
                'country' => 'Japan',
                'created' => '2020-02-08 10:00:00',
                'modified' => '2020-02-08 10:00:00',
            ],
            [
                'name' => 'admin',
                'user_device' => 'PC',
                'os' => 'Windows',
                'age' => 35,
                'country' => 'Japan',
                'created' => '2020-02-09 10:00:00',
                'modified' => '2020-02-09 10:00:00',
            ],
            [
                'name' => 'matsumoto',
                'user_device' => 'スマホ',
                'os' => 'Windows',
                'age' => 35,
                'country' => 'Japan',
                'created' => '2020-02-10 10:00:00',
                'modified' => '2020-02-10 10:00:00',
            ],
            [
                'name' => 'tokino',
                'user_device' => 'スマホ',
                'os' => 'Windows',
                'age' => 35,
                'country' => 'Japan',
                'created' => '2020-02-11 10:00:00',
                'modified' => '2020-02-11 10:00:00',
            ],
            [
                'name' => 'admin',
                'user_device' => 'スマホ',
                'os' => 'Windows',
                'age' => 35,
                'country' => 'Japan',
                'created' => '2020-02-12 10:00:00',
                'modified' => '2020-02-12 10:00:00',
            ],
            [
                'name' => 'matsumoto',
                'user_device' => 'PC',
                'os' => 'Mac',
                'age' => 35,
                'country' => 'USA',
                'created' => '2020-02-13 10:00:00',
                'modified' => '2020-02-13 10:00:00',
            ],
            [
                'name' => 'tokino',
                'user_device' => 'PC',
                'os' => 'Mac',
                'age' => 35,
                'country' => 'USA',
                'created' => '2020-02-14 10:00:00',
                'modified' => '2020-02-14 10:00:00',
            ],
            [
                'name' => 'admin',
                'user_device' => 'PC',
                'os' => 'Mac',
                'age' => 35,
                'country' => 'USA',
                'created' => '2020-02-15 10:00:00',
                'modified' => '2020-02-15 10:00:00',
            ],
            [
                'name' => 'matsumoto',
                'user_device' => 'スマホ',
                'os' => 'Mac',
                'age' => 35,
                'country' => 'USA',
                'created' => '2020-02-16 10:00:00',
                'modified' => '2020-02-16 10:00:00',
            ],
            [
                'name' => 'tokino',
                'user_device' => 'スマホ',
                'os' => 'Mac',
                'age' => 35,
                'country' => 'USA',
                'created' => '2020-02-17 10:00:00',
                'modified' => '2020-02-17 10:00:00',
            ],
            [
                'name' => 'admin',
                'user_device' => 'スマホ',
                'os' => 'Mac',
                'age' => 35,
                'country' => 'USA',
                'created' => '2020-02-18 10:00:00',
                'modified' => '2020-02-18 10:00:00',
            ],
            [
                'name' => 'matsumoto',
                'user_device' => 'PC',
                'os' => 'Mac',
                'age' => 35,
                'country' => 'China',
                'created' => '2020-02-19 10:00:00',
                'modified' => '2020-02-19 10:00:00',
            ],
            [
                'name' => 'tokino',
                'user_device' => 'PC',
                'os' => 'Mac',
                'age' => 35,
                'country' => 'China',
                'created' => '2020-02-20 10:00:00',
                'modified' => '2020-02-20 10:00:00',
            ],
            [
                'name' => 'admin',
                'user_device' => 'PC',
                'os' => 'Mac',
                'age' => 35,
                'country' => 'China',
                'created' => '2020-02-21 10:00:00',
                'modified' => '2020-02-21 10:00:00',
            ],
            [
                'name' => 'matsumoto',
                'user_device' => 'スマホ',
                'os' => 'Mac',
                'age' => 35,
                'country' => 'China',
                'created' => '2020-02-22 10:00:00',
                'modified' => '2020-02-22 10:00:00',
            ],
            [
                'name' => 'tokino',
                'user_device' => 'スマホ',
                'os' => 'Mac',
                'age' => 35,
                'country' => 'China',
                'created' => '2020-02-23 10:00:00',
                'modified' => '2020-02-23 10:00:00',
            ],
            [
                'name' => 'admin',
                'user_device' => 'スマホ',
                'os' => 'Mac',
                'age' => 35,
                'country' => 'China',
                'created' => '2020-02-24 10:00:00',
                'modified' => '2020-02-24 10:00:00',
            ],
        ];
        $table = $this->table('profiles');
        $table->insert($data)->save();
    }
}
